### ISSUE TITLE
DllNotFoundException: iwasm assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by GabrielePicco** [HoloLabInc/IwasmUnity#7]
# Steps to reproduce

- Added the dependency in the manifest.json
- Imported the sample scene
- When clicking on the run button, it throws: DllNotFoundException: iwasm assembly:<unknown assembly> type:<unknown type> member:(null)

# Env details

- Apple M1 Max
- OSX 13.0
- Unity Editor 2021.3.19f
- IwasmUnity: v0.2.0

# Comments

I believe the issue is related to the libiwasm.dylib only being target for Intel 64.

**Comment by ikorin24** [comment]
Yes, IwasmUnity currently does not support Apple silicon Mac.
Only the x64 native library is available now.

See PR #6 for Apple silicon Mac.
It has not been merged yet, but please give it a try.

**Comment by GabrielePicco** [comment]
Thanks @ikorin24 , PR #6 works for me

**Comment by GabrielePicco** [comment]
@ikorin24 I wonder if there is any plan to support WebGL as well

**Comment by ikorin24** [comment]
@GabrielePicco 
> I wonder if there is any plan to support WebGL as well

No, there are currently no plans to support WebGL build.

**Comment by ikorin24** [comment]
PR #6 is merged, that closes this issue.

If you still see the following exception, please confirm your build settings.
Architecture should be 'Intel 64-bit' or 'Apple silicon'. Don't use 'Intel 64-bit + Apple silicon'.

```
System.DllNotFoundException: iwasm assembly:<unknown assembly> type:<unknown type> member:(null)
```

**Comment by GabrielePicco** [comment]
> @GabrielePicco
> 
> > I wonder if there is any plan to support WebGL as well
> 
> No, there are currently no plans to support WebGL build.

Thanks @ikorin24 , is there any specific technical limitation? Wouldn't be enough to include the compiled iwasm runtime also in WebGL? I can try to draft a PR, it would be nice to have wasm working cross platforms

**Comment by ikorin24** [comment]
@GabrielePicco 
We have not tested whether iwasm can be used with WebGL, so we do not know if there are any technical limitations.

If additional discussion of how it works with WebGL is needed, please create a new issue or PR, not here.
PRs are always welcome. Thank you.
