### ISSUE TITLE
Failed to create an instance without reported issues

### ISSUE THREAD

**Issue by GabrielePicco** [HoloLabInc/IwasmUnity#8]
I'm trying to execute the attached `poseidon_hasher.wasm` binary, but the instance is failing on instantiation, without any issue being reported. I can successfully run the hello.wasm example.

Here is the code:

```csharp
private void HelloSample()
{
    try
    {
        if (_engine == null)
        {
            _engine = new Engine();
            _store = new Store(_engine);
        }
        using var module = Module.CreateFromWasm(_store, _wasm);
        var imports = module.CreateImports();
        
        # define extern functions 
        imports.ImportAction("runtime", "exceptionHandler", error =>
        {
            throw new Exception($"{error.ToString()}");
        });
        imports.ImportAction("runtime", "printErrorMessage", context =>
        {
            Debug.Log(context);
        });
        imports.ImportAction("runtime", "writeBufferMessage", context =>
        {
            Debug.Log("Call writeBufferMessage");
        });
        imports.ImportAction("runtime", "showSharedRWMemory", context =>
        {
            Debug.Log("Call showSharedRWMemory");
        });

        using var instance = module.CreateInstance(imports, heapSize: 32 * 1024);
        var run = instance.Exports.GetFunction("circom_version").ToAction();
        run.Invoke();
    }
    catch (Exception ex)
    {
        _text.text = ex.ToString();
        throw;
    }
}
```

The instance created at `instance = IwasmCApi.wasm_instance_new_with_args(module.Store.StoreNative, module.ModuleNative, &importExternVec, null, stackSize, heapSize);` is null, I tried to investigate but there is not reported issue.

For reference, here is a library that succesfully run the same wasm: https://github.com/iden3/circom_runtime/blob/master/build/main.cjs#L112

Thanks in advance for the help!

wasm: https://drive.google.com/file/d/16incxFY0zExj1y-KKELavbWC2gHSsQZM/view?usp=sharing

**Comment by ikorin24** [comment]
Importing functions is wrong.

`"exceptionHandler"` in `poseidon_hasher.wasm` is of type `func (param i32)`, which in C# is `Action<int>`.

<img width="619" alt="s1" src="https://user-images.githubusercontent.com/19363522/234530388-e07f8d41-d1a2-4ba8-bba1-6c26a501826b.png">

If you import it, use `Action<ImportedContext, int>`.

```cs
imports.ImportAction("runtime", "exceptionHandler", (ImportedContext context, int error) =>
{
    throw new Exception(error.ToString());
});
```

And, `poseidon_hasher.wasm` has no function named `"circom_version"`.
Correct name is `"getVersion"`, whose type is `(func (result i32))`. in C#, `Func<int>`


<img width="501" alt="s2" src="https://user-images.githubusercontent.com/19363522/234529105-a42e0f7a-7d84-49c4-b0df-832af0f13e64.png">

So, you should write as following.

```cs
Func<int> getVersion = instance.Exports.GetFunction("getVersion").ToFunc<int>();
int version = getVersion.Invoke();
```


Here is the code that works correctly.

```cs
private void HelloSample()
{
    try
    {
        if (_engine == null)
        {
            _engine = new Engine();
            _store = new Store(_engine);
        }
        using var module = Module.CreateFromWasm(_store, _wasm);
        var imports = module.CreateImports();
        imports.ImportAction("runtime", "exceptionHandler", (ImportedContext context, int error) =>
        {
            throw new Exception(error.ToString());
        });
        imports.ImportAction("runtime", "printErrorMessage", (ImportedContext context) =>
        {
            Debug.Log(context);
        });
        imports.ImportAction("runtime", "writeBufferMessage", (ImportedContext context) =>
        {
            Debug.Log("Call writeBufferMessage");
        });
        imports.ImportAction("runtime", "showSharedRWMemory", (ImportedContext context) =>
        {
            Debug.Log("Call showSharedRWMemory");
        });

        using var instance = module.CreateInstance(imports);
        var getVersion = instance.Exports.GetFunction("getVersion").ToFunc<int>();
        var version = getVersion.Invoke();
        Debug.Log(version);
    }
    catch (Exception ex)
    {
        _text.text = ex.ToString();
        throw;
    }
}
```

**Comment by GabrielePicco** [comment]
thanks for the fast reply @ikorin24, make perfect sense, works now. 
Just curious: did you manage to debug decompiling the wasm to wat or is there a way to see exceptions on the instance creation?

**Comment by GabrielePicco** [comment]
Thanks @ikorin24!
